// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACgswlZAe6tuSCzd3XXLLr0ewxrDyuuvU',
    appId: '1:194958175295:web:62133d32c960e5f8c99c8a',
    messagingSenderId: '194958175295',
    projectId: 'my-workspace-app-26',
    authDomain: 'my-workspace-app-26.firebaseapp.com',
    storageBucket: 'my-workspace-app-26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQvMYFO-X5unp7Rv9r3smsec_uGi1zw8',
    appId: '1:194958175295:android:fa3da60149194a81c99c8a',
    messagingSenderId: '194958175295',
    projectId: 'my-workspace-app-26',
    storageBucket: 'my-workspace-app-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtTBTqGvgwlU_CuMc5TYsnjbUcVRgqyI',
    appId: '1:194958175295:ios:5f033f43d4f08cbdc99c8a',
    messagingSenderId: '194958175295',
    projectId: 'my-workspace-app-26',
    storageBucket: 'my-workspace-app-26.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHtTBTqGvgwlU_CuMc5TYsnjbUcVRgqyI',
    appId: '1:194958175295:ios:5f033f43d4f08cbdc99c8a',
    messagingSenderId: '194958175295',
    projectId: 'my-workspace-app-26',
    storageBucket: 'my-workspace-app-26.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACgswlZAe6tuSCzd3XXLLr0ewxrDyuuvU',
    appId: '1:194958175295:web:522f6e1321f65142c99c8a',
    messagingSenderId: '194958175295',
    projectId: 'my-workspace-app-26',
    authDomain: 'my-workspace-app-26.firebaseapp.com',
    storageBucket: 'my-workspace-app-26.firebasestorage.app',
  );

}